### ISSUE TITLE
Restart button can't be clicked when game is paused...

### ISSUE THREAD

**Issue by H3AR7B3A7** [Mrjsaw/ChessClock#20]
Om die restart button te fixen wanneer spel is gepauseerd moet ik ofwel een clock state 'pause' toevoegen .. Of toch werken met een check op een boolean gelijk ik eerst had gedaan volgens mij. 
Die clockstate = null bij pauseState() is daar voor die selfStart optie om goe te werken wanneer er wordt gepauseerd.

Wat hebt ge het liefst?

**Comment by Mrjsaw** [comment]
Zet een boolean met checks momenteel.

OF

Eventueel 2 state Functions:
pausedState(isStart: Boolean) {
// unhighlight buttons, hide pause button, pause both timers, activate restart if isStart false else inactive
}
runningState(activatedClock : Boolean) { 
//higlight meegegeven clock (true = top, false = bot), unhighlight andere, activate restart & pause, start meegegeven/pause andere
}

**Comment by H3AR7B3A7** [comment]
Heb in laatste pull request de boolean met checks toegepast .. Zie maar of ge dat proper genoeg vind of dat ge liever hebt dat ik het met extra clockState doe...
